name: Test vcpkg ports

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Acquire vcpkg
      uses: actions/checkout@v4
      with:
        repository: "Microsoft/vcpkg"
        path: vcpkg

    - name: Bootstrap vcpkg
      shell: bash
      run: "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"

    - name: Install Mono
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-complete

    - name: Add NuGet sources
      shell: bash
      env:
        VCPKG_EXE: "${{ github.workspace }}/vcpkg/vcpkg"
        FEED_URL: "https://nuget.pkg.github.com/vicroms/index.json"
      run: |
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          sources add \
          -Name "GitHubPackages" \
          -Source "${{ env.FEED_URL }}" \
          -UserName "vicroms" \
          -Password "${{ secrets.PACKAGES_GITHUB_TOKEN }}" \
          -StorePasswordInClearText
        mono `${{ env.VCPKG_EXE }} fetch nuget | tail -n 1` \
          setapikey "${{ secrets.PACKAGES_GITHUB_TOKEN }}" \
          -Source "${{ env.FEED_URL }}"

    - name: Build ports
      shell: bash
      env:
        VCPKG_OVERLAY_PORTS: "${{ github.workspace }}/ports"
        VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/vicroms/index.json,readwrite"
      run: ${{ github.workspace }}/vcpkg/vcpkg install
